-- Baseline of the schema previously created by hibernate ddl-auto=update.
-- Prefer regenerating this with pg_dump (see steps doc) if your dev DB differs.

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('STUDENT', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS resources (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    description   VARCHAR(255),
    url           VARCHAR(255) NOT NULL,
    resource_type VARCHAR(255),
    topic         VARCHAR(255),
    difficulty    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bookmarks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    CONSTRAINT uk_bookmarks_user_resource UNIQUE (user_id, resource_id)
);
